app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager


class User(UserMixin,db.Model):
   __tablename__ = 'users'
   id = db.Column(db.Integer,primary_key = True)
   username = db.Column(db.String(255))
   email=db.Column(db.String(255),unique=True,index=True)
   password_hash=db.Column(db.String(255))
   pass_secure = db.Column(db.String(255))
   about = db.Column(db.String(255))
   profile_pic_path = db.Column(db.String())
   pitch = db.relationship('Pitch', backref='user', lazy='dynamic')
   pitchcom = db.relationship('PitchCom', backref='user', lazy='dynamic')


   @property
   def password(self):
       raise AttributeError('You can`t see this')
   @password.setter
   def password(self, password):
       self.pass_secure = generate_password_hash(password)
   def verify_password(self,password):
       return check_password_hash(self.pass_secure,password)
   def __repr__(self):
       return  {self.username}
   @login_manager.user_loader
   def load_user(user_id):
       return User.query.get(int(user_id))


class Pitch(db.Model):
   __tablename__ = 'pitch'
   id = db.Column(db.Integer, primary_key=True)
   pitch = db.Column(db.String(255))
   user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
   pitchdata = db.relationship('PitchCom', backref='use', lazy='dynamic')
   def save_pitch(self):
       db.session.add(self)

       
class PitchCom(db.Model):
   __tablename__ = 'pitchcom'
   id = db.Column(db.Integer, primary_key=True)
   Pitchcom = db.Column(db.String(255))
   user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
   pitch_id = db.Column(db.Integer, db.ForeignKey("pitch.id"))
   def save_pitchcom(self):
       db.session.add(self)
       db.session.commit()

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import Required

class UpdateProfile(FlaskForm):
   bio = TextAreaField('Tell us your bio.',validators = [Required()])
   submit = SubmitField('Submit')

class PitchForm(FlaskForm):
   pitch = TextAreaField('Write a pitch')
   submit = SubmitField('Submit')

class PitchComForm(FlaskForm):
   pitchcom = TextAreaField('comment on your pitch ')
   submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail


bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
photos = UploadSet('photos',IMAGES)
mail = Mail()


def create_app(config_name):
   app = Flask(__name__)

   # creating app configurations
   app.config.from_object(config_options[config_name])
   app.config['SECRET_KEY'] = '1234'

   # configure UploadSet
   configure_uploads(app,photos)


   # initializing flask extensions
   bootstrap.init_app(app)
   db.init_app(app)
   login_manager.init_app(app)
   mail.init_app(app)

   # registering the Blueprint
   from .main import main as main_blueprint
   app.register_blueprint(main_blueprint)

   # registering the auth Blueprint
   from .auth import auth as auth_blueprint
   app.register_blueprint(auth_blueprint, url_prefix = '/authenticate')

   return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from ..models import User, Pitch, PitchCom
from .. import db,photos
from flask_login import login_required, current_user
from .forms import PitchComForm,PitchForm,UpdateProfile
# import markdown2


@main.route('/')
def index():

   return render_template('index.html')

@main.route('/blog', methods = ['GET','POST'])
@login_required
def pitch():
   form = PitchForm()
   title = 'The PITCHES'
   if form.validate_on_submit():
       new_pitch = Pitch(pitch=form.pitch.data, user_id=current_user.id)

       db.session.add(new_pitch)
       db.session.commit()
       return redirect(url_for('.allpitchs'))

   return render_template("blog.html", title = title, PitchForm= form)


@main.route('/blog/<int:id>',methods=['GET', 'POST'])
@login_required
def pitchid(id):
   form = PitchComForm()
   pitch = Pitch.query.get(id)
   if form.validate_on_submit():
       pitch = form.pitchcom.data
       new_pitchcom = PitchCom(Pitchcom=pitch, pitch_id=id, user=current_user)
       new_pitchcom.save_pitchcom()
   pitchz = PitchCom.query.filter_by(pitch_id=id).all()
   return render_template('blogs.html',PitchForm=form,comments = pitchz,pitch=pitch )

@main.route('/blogs')
@login_required
def allpitchs():
   title = 'all pitchs'
   pitch = Pitch.query.order_by(Pitch.id).all()
   return render_template("bio.html", title=title, pitch=pitch )

@main.route('/user/<uname>')
@login_required
def profile(uname):
   user = User.query.filter_by(username = uname).first()

   if user is None:
       abort(404)

   return render_template("profile/profile.html", user = user)


@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
   user = User.query.filter_by(username = uname).first()
   if user is None:
       abort(404)

   form = UpdateProfile()

   if form.validate_on_submit():
       user.bio = form.bio.data

       db.session.add(user)
       db.session.commit()

       return redirect(url_for('.profile',uname=user.username))

   return render_template('profile/update.html',form =form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
   user = User.query.filter_by(username = uname).first()
   if 'photo' in request.files:
       filename = photos.save(request.files['photo'])
       path = f'photos/{filename}'
       user.profile_pic_path = path
       db.session.commit()
   return redirect(url_for('main.profile',uname=uname))

app/templates/base.html
{% extends 'bootstrap/base.html' %}
{% import 'bootstrap/wtf.html' as wtf%}
<!DOCTYPE html>
<html>
  <head>
      <meta charset="utf-8">
  </head>       <!-- Styles block -->
{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/styles.css')}}">
<link href="https://fonts.googleapis.com/css?family=BenchNine%7CJust+Another+Hand%7CLuckiest+Guy&display=swap" rel="stylesheet">
<link href="https://fontawesome.com/css/fontawesome.css" rel="stylesheet">
<script src="https://kit.fontawesome.com/daec53f9a1.js"></script>
{% endblock %}
<!-- Navbar block  -->
{% block navbar %}
   {% include 'navbar.html' %}
{% endblock %}
<body>
{% block content %}
{% endblock %}
</body>
</html>

app/templates/bio.html
{% extends 'base.html' %}
{% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="text-center">
                <a href="/blog">Pitch</a><br> <hr>
                <h1>POSTED PITCHES</h1>
                {% for pitch in pitch %}
                <blockquote>
                    {{pitch.pitch}}
                </blockquote>
                <a href="/blog/{{pitch.id}}"><span class="glyphicon glyphicon-comment"></span></a>
                <h1>{{pitch.user.username}}</h1>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

app/templates/blog.html
{% extends 'base.html' %}

{% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="text-center">
                    <h1>POST A PITCH</h1>

                    {{wtf.quick_form(PitchForm)}}
            </div>
        </div>
    </div>
</div>



{%endblock%}

app/templates/blogs.html
{% extends 'base.html' %}
{% block content %}

<div class="container-fluid">
   <div class="row">
      <div class="col-sm-12">
         <div class="text-center">
               <h1>PITCHES</h1>
               <p> {{pitch.pitch}}</p>
                 {%if comments%}
                 {% for comment in comments %}
                    <p>{{comment.Pitchcom}}</p>
        
        {{wtf.quick_form(PitchForm)}}
         </div>
      </div>
   </div>
</div>

{%endblock%}

app/templates/index.html
{% extends 'base.html'%}
{% block content%}
<body>
    <div class="row">
        <div class="col-sm-12">
            <div class="text-center">
                <a  href="./blog"><button class="btn btn-danger btn-lg text-center">Create Pitch</button></a>
            </div>
        </div>
    </div>   
</body>

{% endblock %}

app/templates/macros.html
{% macro displayComments(comments) %}
   {% for comment in comments %}

   <table style="width:100%">
     <tr>
       <th>Title</th>
       <th>Comment</th>
       <th>User</th>
       <th>Delete</th>
     </tr>
     <tr>
       <td>{{comment.title}}</td>
       <td>{{comment.comment}}</td>
       <td>{{comment.user.username}}</td>
       <td><a href="{{url_for('main.del_comment',pitch_id = comment.pitch_id, comment_id = comment.id)}}"><button type="button" name="button" class="btn btn-warning">Delete Comment</button></a></td>
     </tr>
   </table>
   {% endfor %}
{% endmacro %}

app/templates/navbar.html
<div class="navbar navbar-default navbar-inverse"  style='margin-bottom: 0px;' role="navigation" id="navigate">
    <div class="container-fluid">
     <div class="navbar-header">
       <button type="button" data-toggle="collapse" data-target=".navbar-collapse">
                 <span class="sr-only">Toggle navigation</span></button>
    </div>
    
    <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
            </ul>
            <ul class="nav navbar-nav">
                <li><a href="{{url_for('auth.login')}}">create</a></li>
            </ul>
    
    
       <ul class="nav navbar-nav navbar-right">
         {% if current_user.is_authenticated %}
            <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
    
    
         <li><a href="{{url_for('auth.logout')}}">Sign out </a></li>
         {% else %}
         <li><a href="{{url_for('auth.login')}}">Sign in </a></li>
         {% endif %}
       </ul>
    </div>
    
    </div>
</div>

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div>
                {% if user == current_user %}
                <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit Profile</a>
                {% endif %}
            </div>

            <!-- displaying Username -->
            <div>
                <h3> {{user.username| capitalize}} </h3>

                <!-- displaying user bio -->
                {% if user.bio %}
                <p>{{user.bio}}</p>
                {% else %}
                <p>{{user.username| capitalize}} has no about</p>
                {% endif %}
            </div>

            <div>
                {% if user.profile_pic_path %}
                <img src="url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">

                {%else%}
                <p>Missing Profile Picture</p>

                {%endif%}

                {% if user == current_user %}

                <form action="{{url_for('main.update_pic',uname=user.username)}}" method="POST" enctype="multipart/form-data"></form>
                <input type="file" name="photo" class="form-control" required>
                <input type="submit">
                {%endif%}
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<body>
    <div class="bg-img">
        <div class="row">
            <div class="col-sm-12">
                {{wtf.quick_form(form)}}
            </div>
        </div>
    </div>
</body>

{% endblock %}